tippecanoe -o brussels_ultimate_v2.pmtiles --force \
  --maximum-zoom=17 \
  --attribution="OpenStreetMap contributors" \
  --generate-ids \
  --drop-densest-as-needed \
  --extend-zooms-if-still-dropping \
  -L landuse:landuse.json \
  -L pedestrian:pedestrian.json \
  -L cycling:cycling.json \
  -L furniture:furniture.json \
  -L infra:infra.json \
  -L green:green.json \
  -L buildings:buildings.json \
  -L buildings_parts:buildings_parts.json \
  -L poi:poi.json \
  -L roads:roads.json \
  -L water:water.json \
  -L railways:railways.json \
  -L boundaries:boundaries.json
